version: "3"

services:
  bark:
    container_name: bark
    image: bark
    build: .
    environment:
      NVIDIA_VISIBLE_DEVICES: ALL
      TMPDIR: /tmp
    volumes:
      - ./hub/:/bark/.cache/huggingface/hub/
      - ./models/:/bark/bark-gui/models/
    ports:
      - "17860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu,video]
              count: all

